export const fieldValues = {
  frequencies: [
    "od",
    "bd",
    "hs",
    "sos",
    "td",
    "after 15 days",
    "stat",
    "once a month",
    "qd",
    "once a week",
    "once in 15 days"
  ],
  dosages: [
    "1 tsp",
    "1/2 tab",
    "1 tab",
    "2 tabs",
    "2 tsp",
    "1 drop",
    "2 puffs",
    "1 puff",
    "1 rotacap"
  ],
  durations: [
    "10 days",
    "20 days",
    "3 days",
    "5 days",
    "2 months",
    "1 month",
    "1 months",
    "7 days",
    "5",
    "1 week",
    "2 days",
    "3 months",
    "6 months",
    "4 days",
    "15 days",
    "3 weeks",
    "4 months",
    "6 weeks"
  ],
  specialComments: [
    "8am",
    "empty stomach",
    "after breakfast",
    "9pm",
    "1/2 hour before meals",
    "after lunch",
    "after meals",
    "8am, 6pm",
    "6pm",
    "4pm",
    "morning",
    "locally",
    "12pm",
    "1/2 hour before breakfast and dinner",
    "after breakfast and dinner",
    "after dinner",
    "2pm",
    "with meals",
    "7am",
    "once a month",
    "for headache",
    "before meals",
    "1/2 hour before breakfast",
    "evening",
    "before breakfast, before lunch",
    "7pm",
    "10pm",
    "11am",
    "6am"
  ]
};
